### PR TITLE
use UNKNOWN status for internal exceptions in check_cluster 

### PR DESCRIPTION
**Pull request by oktopuz**
It will prevent generating CRITICAL alert when check_cluster can't connect to redis due to DNS issues.
Also it should not alert as CRITICAL when there are no hosts with a cluster check in a region.

### CODE REVIEW

**Comment by somic** [comment]
ship

**Comment by solarkennedy** [comment]
@keymone  can you review this?

**Comment by oktopuz** [comment]
@keymone ^^

**Comment by bobtfish** [comment]
Proxying for @keymone - ship!

**Pull request merged**
