### PR TITLE
Allow realert_every to be written in human readable formats

### PR DESCRIPTION
**Pull request by pauloconnor**
This makes writing times more consistent.

### CODE REVIEW

**Comment by solarkennedy** [comment]
realert_every is not a time unit

**Comment by solarkennedy** [comment]
Here is the docstring for the input: https://github.com/Yelp/puppet-monitoring_check/blob/master/manifests/init.pp#L41

@pauloconnor @bobtfish can you revert this change so it doesn't mislead users?
I understand it would be nice if it was a time unit, but it can't be due to the way that alerts have to correlate with events in sensu.

**Comment by pauloconnor** [comment]
It was reverted 2 hours ago.

**Comment by solarkennedy** [comment]
ty

**Pull request merged**
