### PR TITLE
add environment variables parameter

### PR DESCRIPTION
**Pull request by jglukasik**
I tried to set environment variables at the start of $command, but then the string fails the validation that checks that a full path is being used.

### CODE REVIEW

**Comment by solarkennedy** [comment]
but if using a full path is not a hard requirement (it isn't), how about relaxing the string validation instead of adding a new parameter?

**Comment by jglukasik** [comment]
The check I will be running requires sudo as well. A full path for use with sudo is a hard(er) requirement, right?

**Comment by solarkennedy** [comment]
It should only validate the full path if needs_sudo I suppose.

**Comment by jglukasik** [comment]
Closing this PR. Issues with the interplay between sudo/environment variables would make this too complex. Instead, a wrapper script will be written for this specific case I have.

**Pull request closed without merging**
